[package]
name = "sample"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
dlpackrs = { path = "../..", version = "0.2.0-dev.0" }
ndarray = { version = "0.15", features = ["approx"] }
